# All trapdoors disabled EXCEPT pale oak

on rightclick:
    if clicked block is set:
        if type of clicked block contains "trapdoor":
            if type of clicked block is not pale oak trapdoor:
                cancel event

on place:
    if event-item is set:
        if type of event-item contains "trapdoor":
            if type of event-item is not pale oak trapdoor:
                cancel event
                send "&cTrapdoors are disabled!" to player
